services:
  - type: web
    name: projeto-django
    env: python
    buildCommand: ""
    startCommand: gunicorn projeto_django_organizado.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projeto_django_organizado.settings
      - key: SECRET_KEY
        value: sua_chave_secreta_segura
      - key: PYTHON_VERSION
        value: "3.11"
