# Generated by Django 5.2.1 on 2025-05-30 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Água', 'Água'), ('Gás', 'Gás'), ('Eletricidade', 'Eletricidade')], max_length=20)),
                ('consumo', models.FloatField(blank=True, null=True)),
                ('apartamentos', models.IntegerField(blank=True, null=True)),
                ('consumo_por_apartamento', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('volume_inicial', models.FloatField(blank=True, null=True)),
                ('volume_atual', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
