# Generated by Django 4.2 on 2025-06-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoRVN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('consumo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apartamentos', models.IntegerField(blank=True, null=True)),
                ('consumo_por_apartamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('volume_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
