# Generated by Django 4.2 on 2025-06-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0003_botija_alter_registroconsumo_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Botija',
        ),
        migrations.AddField(
            model_name='registroconsumo',
            name='botija_01',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroconsumo',
            name='botija_02',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroconsumo',
            name='botija_03',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroconsumo',
            name='botija_04',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroconsumo',
            name='tipo',
            field=models.CharField(choices=[('Água', 'Água'), ('Gás', 'Gás'), ('Eletricidade', 'eletricidade')], max_length=20),
        ),
    ]
