# Generated by Django 4.2 on 2025-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0004_delete_botija_registroconsumo_botija_01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsumo',
            name='hospedes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
