# Generated by Django 4.2 on 2025-06-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0005_registroconsumo_hospedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumorvn',
            name='botija_01',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumorvn',
            name='botija_02',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumorvn',
            name='botija_03',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumorvn',
            name='botija_04',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumorvn',
            name='hospedes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
