# Generated by Django 4.2 on 2025-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0006_consumorvn_botija_01_consumorvn_botija_02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumorvn',
            name='consumo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumorvn',
            name='consumo_por_apartamento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumorvn',
            name='tipo',
            field=models.CharField(choices=[('Água', 'Água'), ('Gás', 'Gás'), ('Eletricidade', 'eletricidade')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consumorvn',
            name='volume_atual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumorvn',
            name='volume_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
