# Generated by Django 4.2 on 2025-06-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0008_remove_registroconsumo_hospedes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumorvn',
            name='botija_03',
        ),
        migrations.RemoveField(
            model_name='consumorvn',
            name='botija_04',
        ),
    ]
