# Generated by Django 4.2 on 2025-06-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0009_remove_consumorvn_botija_03_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumorvn',
            name='botija_03',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consumorvn',
            name='botija_04',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
