# Generated by Django 4.2 on 2025-06-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0010_consumorvn_botija_03_consumorvn_botija_04'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumorvn',
            name='botija_03',
        ),
        migrations.RemoveField(
            model_name='consumorvn',
            name='botija_04',
        ),
    ]
