# Generated by Django 4.2 on 2025-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0011_remove_consumorvn_botija_03_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsumo',
            name='hospedes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
