# Generated by Django 4.2 on 2025-06-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0012_registroconsumo_hospedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsumo',
            name='consumo_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
