# Generated by Django 4.2 on 2025-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_pagina', '0013_registroconsumo_consumo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumorvn',
            name='consumo_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
